### ISSUE TITLE
Assignment deadline

### ISSUE THREAD

**Issue by Pablo-Paniagua** [Digital-Humans-23/a3#1]
Is it correct that the deadline for this assignment is the 11th of April? Is there any reason in particular for it being:
a) Shorter than the previous (2 weeks)
b) In the middle of the easter holiday

Thanks in advance for the clarification.

PS. It would be greatly appreciated if it was after Easter given that those days we are not really meant to work on university assignments.

**Comment by yz-cnsdqz** [comment]
The due date of a3 is extended to April 20, which is the same date of Assignment 4 out.
