### ISSUE TITLE
Join() Missing Argument Error

### ISSUE THREAD

**Issue by aneeshra** [Digital-Humans-23/a3#10]
I am attempting to run app_multiview_mocap_ZJUMocap.py. 

However, I keep getting the below error, and I am not sure how to fix this.

cfgall_shaper = ConfigCreator(args.cfg_shaper)  

File (from a3 directory)\venv\lib\site-packages\lisst-0.2.1-py3.10.egg\lisst\utils\config_creator.py", line 16, in __init__    exppath = os.path.join( *(__file__.split('/')[:-2]) )TypeError: join() missing 1 required positional argument: 'path'

Thanks in advance!

**Comment by bottad** [comment]
Did you find a solution for this? I get the same error and don't really know what to do...
