### ISSUE TITLE
Physical meaning of rotation vector represented in 6D

### ISSUE THREAD

**Issue by Wilboludriver** [Digital-Humans-23/a3#13]
Hi all,

I traced back through the files, but didn't find any explaination for the 6D representation of rotation. Though I passed the test with the the regularization from the J_rotcont tensor, I still don't know the physical meaning of this computation. 

Best,
ZY

**Comment by yz-cnsdqz** [comment]
here is the paper: https://arxiv.org/abs/1812.07035

It empirically surpasses quaternion for IK.

**Comment by Wilboludriver** [comment]
> here is the paper: https://arxiv.org/abs/1812.07035
> 
> It empirically surpasses quaternion for IK.

Thanks very much for sharing the link!
