### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by emilia-szymanska** [Digital-Humans-23/a3#2]
I have a couple of problems I encountered while trying to set everything up, I would like to ask for help:
1. I am in venv, I intalled the tools from requirements.txt and I surely have numpy (when I tried to run pip install numpy I got
_Requirement already satisfied: numpy in /home/emilia/digital_humans/dg/lib/python3.8/site-packages (1.24.2)_ ). Despite that, when I want to try running tests locally with pytest I get:

ImportError while importing test module '/home/emilia/digital_humans/a3-emilia-szymanska/tests/test01.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test01.py:5: in <module>
    import numpy as np
ImportError: No module named numpy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2. Pytest was not in requirements, I installed it manually - shouldn't it be in requirements.txt if we want to run the tests with it?
3. When running the demo_01_sample_bodies in the second cell I get an error:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I guess I don't have cuda to run the notebook on it, I can use only CPU, so what should I change in the demo to check if I installed everything properly?

**Comment by yz-cnsdqz** [comment]
Thanks for the feedback. 
1. This is because the pytest does not use the current python environment. You could optionally try `python -m pytest ***`.
2. Yes, you can install pytest manually in order to test it locally.
3. Yes, the demo scripts use cuda by default. You could set its device to CPU. Please feel free to explore.

**Comment by emilia-szymanska** [comment]
1. Thank you, it helped.
3. I tried to explore, I set it to CPU and got the aforementioned error, I tried solutions in [here](https://stackoverflow.com/questions/56369030/runtimeerror-attempting-to-deserialize-object-on-a-cuda-device) and then I get an error of "AttributeError: 'dict' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.". I looked for solutions for LISSTCore, but Google doesn't show much for LISST. I think this error is LISST-specific and trying what is proposed by the interpreter is focused on torch. I would be grateful for help in making the demos work on CPU because as I see similar steps are done in the file for task 1, so for CPU-users (I guess many of us) it would mean problems again.

**Comment by meyerdav** [comment]
Using a CPU I am also running into problems. In the script files (which we need to generate the test files, right?), there is no way to change the loading behavior of Lisst. Lisst however, by default assumes GPU. If the scripts would use our local LISST installation we could fix this manually. But like this we cannot or am I overseeing something?

**Comment by yz-cnsdqz** [comment]
Regarding the device error in e.g. demo 1, you could look into `shaper.load()` or `lisst/models/body.py, Line 56`, and replace `ckpt = torch.load(model_path)` to `ckpt = torch.load(model_path, , map_location=torch.device('cpu'))` as a temporary solution. You could check [here](https://discuss.pytorch.org/t/is-map-location-in-torch-load-and-model-load-state-dict-independent-from-device-in-to/99983) for more details. For demo2, you could fix the problem in a similar way.

Thanks for your feedback anyway, I will update the code in the next version :)

**Comment by emilia-szymanska** [comment]
Perfect, now it works, thank you! Just to make sure before closing the issue - you mentioned it "as a temporary solution". Should we then keep the changes when running the non-demo code?

**Comment by yz-cnsdqz** [comment]
It is up to you, because the test scripts only read your result files for grading.

**Comment by emilia-szymanska** [comment]
Okay, thank you for help!
