### ISSUE TITLE
Running the code with CPU

### ISSUE THREAD

**Issue by emilia-szymanska** [Digital-Humans-23/a3#6]
I don't have a GPU and I tried running the code locally. I didn't have the patience to wait for the first iteration to finish, so my question is - is the bad implementation a problem or is it a matter of it taking so long with CPU? If the second one, is there any option to get access to some GPU? (I don't know if running it on Euler would change anything or if the code can be converted to run on e.g. Google Colab)

**Comment by yz-cnsdqz** [comment]
You can check your log. In principle, CPU running should not take very long. For example, in my case on CPU, I have `[iter_inner= 0] PROJ=176.800, SPRIOR=0.000, PPRIOR=0.000, SMOOTH=0.000, TIME=0.34`, which means one iteration takes ~0.34seconds. And here is my CPU info:
```
Model name:                      AMD Ryzen Threadripper 2920X 12-Core Processor
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         1750.814
CPU max MHz:                     3500.0000
CPU min MHz:                     2200.0000
```

**Comment by emilia-szymanska** [comment]
I just got explained that using loops with pytorch is not a good solution (my log data is TIME=21.99). I will try to implement a pytorch-like operations and then I will come back to this issue to say whether it helps (I hope this is it).

**Comment by emilia-szymanska** [comment]
I just managed to transform my 4 nested loops into pytorch operations and now it takes 0.3 seconds for iteration. Thank you for the help!
