### ISSUE TITLE
Some Clarifications regarding Exercise 2/3

### ISSUE THREAD

**Issue by Joshua31415** [Digital-Humans-23/a3#7]
Hi, I would like to ask for clarification regarding the following:
- in exercise 2 we have to differentiate "early" and "late" stages of the optimization. I couldn't find any indication as to how these are actually defined so I set the early stages to the first 25% of the iterations. This passes the test but seems a bit arbitrary to me. Are we supposed to decide this number on our own or did I miss a variable that indicates a number for this in the code?
- the exercise 3 description defines the temporal smoothness loss for joint positions as the sum of all the absolute distances. Is this supposed to be the mean instead of the sum in the implementation? If I just sum up all the values I get gigantic loss values leading to unstable optimization. Using the mean works much better but technically doesn't match the exercise description.

**Comment by yz-cnsdqz** [comment]
- Yes, you are supposed to decide this number by yourselves. There is no absolute definitions on the "early" and "late" stage.
- Using "mean" or "sum" is what you need to explore. The exercise description is just an example. It can be formulated in that way, but that is not the only way.
