### ISSUE TITLE
Unable to pass Ex03

### ISSUE THREAD

**Issue by Milkiananas** [Digital-Humans-23/a3#9]
Dear all,
It seems that reaching the provided target joint velocity within a tolerance of 0.08 is too difficult. I though one has to guess the very original implementation by reverse engineering in order to meet the target. Just curious, has anyone succeeded in passing it?

**Comment by yz-cnsdqz** [comment]
FYI, as a TA, I can see the results of all students. Some people have already passed all tests in auto grading.

**Comment by Joshua31415** [comment]
As a followup question since I’m also struggling to reach the score: are we allowed to change the parameters (e.g. loss weights) or do we have to use the default ones?

**Comment by yz-cnsdqz** [comment]
hi, it is not necessary to use the default ones. You are free to use other hyper-parameters.

**Comment by Joshua31415** [comment]
Ok, thanks for the quick reply!

**Comment by meyerdav** [comment]
A follow up question on this one: Given that the test file takes the norms between the our velocities and your test file, this implies that we can also be too smooth, right? Does this make sense?
